/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package school.management;

/**
 *
 * @author AKRAMUL
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BMain = new javax.swing.JButton();
        BAddStudent = new javax.swing.JButton();
        BRemoveStudent = new javax.swing.JButton();
        BAddTeacher = new javax.swing.JButton();
        BRemoveTeacher = new javax.swing.JButton();
        BViewStudent = new javax.swing.JButton();
        BViewTeacher = new javax.swing.JButton();
        BStudentInfo = new javax.swing.JButton();
        BTeacherInfo = new javax.swing.JButton();
        BExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Main = new javax.swing.JMenuItem();
        CreateAccount = new javax.swing.JMenuItem();
        ChPassword = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Students = new javax.swing.JMenu();
        AddStudent = new javax.swing.JMenuItem();
        RemoveStudent = new javax.swing.JMenuItem();
        ViewStudentList = new javax.swing.JMenuItem();
        Teachers = new javax.swing.JMenu();
        AddTeachers = new javax.swing.JMenuItem();
        RemoveTeachers = new javax.swing.JMenuItem();
        ViewTeachersList = new javax.swing.JMenuItem();
        Informaiton = new javax.swing.JMenu();
        StudentsInfo = new javax.swing.JMenuItem();
        TeachersInfo = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(null);

        BMain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Home.png"))); // NOI18N
        BMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BMain.setPreferredSize(new java.awt.Dimension(75, 35));
        BMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMainActionPerformed(evt);
            }
        });
        jPanel1.add(BMain);
        BMain.setBounds(10, 100, 302, 35);

        BAddStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Add Student.png"))); // NOI18N
        BAddStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BAddStudent.setPreferredSize(new java.awt.Dimension(75, 35));
        BAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddStudentActionPerformed(evt);
            }
        });
        jPanel1.add(BAddStudent);
        BAddStudent.setBounds(10, 140, 302, 35);

        BRemoveStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BRemoveStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Remove Student.png"))); // NOI18N
        BRemoveStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BRemoveStudent.setPreferredSize(new java.awt.Dimension(75, 35));
        BRemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRemoveStudentActionPerformed(evt);
            }
        });
        jPanel1.add(BRemoveStudent);
        BRemoveStudent.setBounds(10, 180, 302, 35);

        BAddTeacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BAddTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Add Teacher.png"))); // NOI18N
        BAddTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BAddTeacher.setPreferredSize(new java.awt.Dimension(75, 35));
        BAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(BAddTeacher);
        BAddTeacher.setBounds(10, 220, 303, 35);

        BRemoveTeacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BRemoveTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Remove Teacher.png"))); // NOI18N
        BRemoveTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BRemoveTeacher.setPreferredSize(new java.awt.Dimension(75, 35));
        BRemoveTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRemoveTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(BRemoveTeacher);
        BRemoveTeacher.setBounds(10, 260, 305, 35);

        BViewStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BViewStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/View Student.png"))); // NOI18N
        BViewStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BViewStudent.setPreferredSize(new java.awt.Dimension(75, 35));
        BViewStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BViewStudentActionPerformed(evt);
            }
        });
        jPanel1.add(BViewStudent);
        BViewStudent.setBounds(10, 300, 305, 35);

        BViewTeacher.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BViewTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/View Teacher.png"))); // NOI18N
        BViewTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BViewTeacher.setPreferredSize(new java.awt.Dimension(75, 35));
        BViewTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BViewTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(BViewTeacher);
        BViewTeacher.setBounds(10, 340, 306, 35);

        BStudentInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BStudentInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Student Information.png"))); // NOI18N
        BStudentInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BStudentInfo.setPreferredSize(new java.awt.Dimension(75, 35));
        BStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BStudentInfoActionPerformed(evt);
            }
        });
        jPanel1.add(BStudentInfo);
        BStudentInfo.setBounds(10, 380, 306, 35);

        BTeacherInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTeacherInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Teacher Information.png"))); // NOI18N
        BTeacherInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BTeacherInfo.setPreferredSize(new java.awt.Dimension(75, 35));
        BTeacherInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTeacherInfoActionPerformed(evt);
            }
        });
        jPanel1.add(BTeacherInfo);
        BTeacherInfo.setBounds(10, 420, 305, 35);

        BExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Exit R.png"))); // NOI18N
        BExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BExit.setPreferredSize(new java.awt.Dimension(75, 35));
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });
        jPanel1.add(BExit);
        BExit.setBounds(10, 460, 304, 35);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Stencil Std", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("School Management System ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 0, 860, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background Image/ak.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-60, -200, 1340, 920);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background Image/123 (2).png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 70, 890, 480);

        File.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Settings_30px.png"))); // NOI18N
        File.setText("File");
        File.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        Main.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Home_30px_2.png"))); // NOI18N
        Main.setText("Home");
        Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainActionPerformed(evt);
            }
        });
        File.add(Main);

        CreateAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Checked_User_Male_30px.png"))); // NOI18N
        CreateAccount.setText("Create Account");
        CreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountActionPerformed(evt);
            }
        });
        File.add(CreateAccount);

        ChPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ChPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Denied_30px_1.png"))); // NOI18N
        ChPassword.setText("Delete User");
        ChPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChPasswordActionPerformed(evt);
            }
        });
        File.add(ChPassword);

        Exit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Shutdown_30px.png"))); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        MenuBar.add(File);

        Students.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Students_30px.png"))); // NOI18N
        Students.setText("Students");
        Students.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsActionPerformed(evt);
            }
        });

        AddStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Add_User_Male_30px.png"))); // NOI18N
        AddStudent.setText("Add Student");
        AddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentActionPerformed(evt);
            }
        });
        Students.add(AddStudent);

        RemoveStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RemoveStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Denied_30px.png"))); // NOI18N
        RemoveStudent.setText("Remove Student");
        RemoveStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveStudentActionPerformed(evt);
            }
        });
        Students.add(RemoveStudent);

        ViewStudentList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewStudentList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_User_Group_30px.png"))); // NOI18N
        ViewStudentList.setText("View Student List");
        ViewStudentList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStudentListActionPerformed(evt);
            }
        });
        Students.add(ViewStudentList);

        MenuBar.add(Students);

        Teachers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Classroom_30px.png"))); // NOI18N
        Teachers.setText("Teachers");
        Teachers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        AddTeachers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddTeachers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_School_Director_30px.png"))); // NOI18N
        AddTeachers.setText("Add Teachers");
        AddTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTeachersActionPerformed(evt);
            }
        });
        Teachers.add(AddTeachers);

        RemoveTeachers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RemoveTeachers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Man_face_30px.png"))); // NOI18N
        RemoveTeachers.setText("Remove Teachers");
        RemoveTeachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveTeachersActionPerformed(evt);
            }
        });
        Teachers.add(RemoveTeachers);

        ViewTeachersList.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewTeachersList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Conference_30px.png"))); // NOI18N
        ViewTeachersList.setText("View Teachers List");
        ViewTeachersList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewTeachersListActionPerformed(evt);
            }
        });
        Teachers.add(ViewTeachersList);

        MenuBar.add(Teachers);

        Informaiton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_More_Info_30px.png"))); // NOI18N
        Informaiton.setText("Information");
        Informaiton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        StudentsInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StudentsInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_User_Group_30px.png"))); // NOI18N
        StudentsInfo.setText("Students");
        StudentsInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsInfoActionPerformed(evt);
            }
        });
        Informaiton.add(StudentsInfo);

        TeachersInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TeachersInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Conference_30px.png"))); // NOI18N
        TeachersInfo.setText("Teachers");
        TeachersInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeachersInfoActionPerformed(evt);
            }
        });
        Informaiton.add(TeachersInfo);

        MenuBar.add(Informaiton);

        Help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Help_30px.png"))); // NOI18N
        Help.setText("Help");
        Help.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuBar.add(Help);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountActionPerformed
        dispose();
        CreateAccount framecacc = new CreateAccount();
        framecacc.setVisible(true);
    }//GEN-LAST:event_CreateAccountActionPerformed

    private void ChPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChPasswordActionPerformed
        dispose();
        ChangePassword framecpass = new ChangePassword();
        framecpass.setVisible(true);
    }//GEN-LAST:event_ChPasswordActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed

    }//GEN-LAST:event_FileActionPerformed

    private void AddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentActionPerformed
        dispose();
        StudentAdd frameadds = new StudentAdd();
        frameadds.setVisible(true);
    }//GEN-LAST:event_AddStudentActionPerformed

    private void RemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveStudentActionPerformed
        dispose();
        StudentRemove frameRemove = new StudentRemove();
        frameRemove.setVisible(true);
    }//GEN-LAST:event_RemoveStudentActionPerformed

    private void ViewStudentListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStudentListActionPerformed
        dispose();
        StudentList framelist = new StudentList();
        framelist.setVisible(true);
    }//GEN-LAST:event_ViewStudentListActionPerformed

    private void StudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentsActionPerformed

    private void AddTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTeachersActionPerformed
        dispose();
       TeacherAdd frameaddT = new TeacherAdd();
       frameaddT.setVisible(true);
    }//GEN-LAST:event_AddTeachersActionPerformed

    private void RemoveTeachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTeachersActionPerformed
        dispose();
        TeacherRemove frameremove = new TeacherRemove();
        frameremove.setVisible(true);
    }//GEN-LAST:event_RemoveTeachersActionPerformed

    private void ViewTeachersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewTeachersListActionPerformed
        dispose();
        TeacherList frameList = new TeacherList();
        frameList.setVisible(true);
    }//GEN-LAST:event_ViewTeachersListActionPerformed

    private void StudentsInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsInfoActionPerformed
        dispose();
        StudentInfo framesinfo = new StudentInfo();
        framesinfo.setVisible(true);
    }//GEN-LAST:event_StudentsInfoActionPerformed

    private void TeachersInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeachersInfoActionPerformed
        dispose();
        TeacherInfo frameInfo = new TeacherInfo();
        frameInfo.setVisible(true);
    }//GEN-LAST:event_TeachersInfoActionPerformed

    private void BMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMainActionPerformed
        dispose();
        Home framemain = new Home();
        framemain.setVisible(true);
    }//GEN-LAST:event_BMainActionPerformed

    private void BAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddStudentActionPerformed
        dispose();
        StudentAdd frameadds = new StudentAdd();
        frameadds.setVisible(true);
    }//GEN-LAST:event_BAddStudentActionPerformed

    private void BRemoveStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRemoveStudentActionPerformed
        dispose();
        StudentRemove frameRemove = new StudentRemove();
        frameRemove.setVisible(true);
    }//GEN-LAST:event_BRemoveStudentActionPerformed

    private void BAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddTeacherActionPerformed
        dispose();
        TeacherAdd frameaddT = new TeacherAdd();
        frameaddT.setVisible(true);
    }//GEN-LAST:event_BAddTeacherActionPerformed

    private void BRemoveTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRemoveTeacherActionPerformed
        dispose();
        TeacherRemove frameremove = new TeacherRemove();
        frameremove.setVisible(true);
    }//GEN-LAST:event_BRemoveTeacherActionPerformed

    private void BViewStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BViewStudentActionPerformed
        dispose();
        StudentList framelist = new StudentList();
        framelist.setVisible(true);
    }//GEN-LAST:event_BViewStudentActionPerformed

    private void BViewTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BViewTeacherActionPerformed
        dispose();
        TeacherList frameList = new TeacherList();
        frameList.setVisible(true);
    }//GEN-LAST:event_BViewTeacherActionPerformed

    private void BStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BStudentInfoActionPerformed
        dispose();
        StudentInfo framesinfo = new StudentInfo();
        framesinfo.setVisible(true);
    }//GEN-LAST:event_BStudentInfoActionPerformed

    private void BTeacherInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTeacherInfoActionPerformed
        dispose();
        TeacherInfo frameInfo = new TeacherInfo();
        frameInfo.setVisible(true);
    }//GEN-LAST:event_BTeacherInfoActionPerformed

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BExitActionPerformed

    private void MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainActionPerformed
        dispose();
        Home framemain = new Home();
        framemain.setVisible(true);
    }//GEN-LAST:event_MainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddStudent;
    private javax.swing.JMenuItem AddTeachers;
    private javax.swing.JButton BAddStudent;
    private javax.swing.JButton BAddTeacher;
    private javax.swing.JButton BExit;
    private javax.swing.JButton BMain;
    private javax.swing.JButton BRemoveStudent;
    private javax.swing.JButton BRemoveTeacher;
    private javax.swing.JButton BStudentInfo;
    private javax.swing.JButton BTeacherInfo;
    private javax.swing.JButton BViewStudent;
    private javax.swing.JButton BViewTeacher;
    private javax.swing.JMenuItem ChPassword;
    private javax.swing.JMenuItem CreateAccount;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenu Help;
    private javax.swing.JMenu Informaiton;
    private javax.swing.JMenuItem Main;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem RemoveStudent;
    private javax.swing.JMenuItem RemoveTeachers;
    private javax.swing.JMenu Students;
    private javax.swing.JMenuItem StudentsInfo;
    private javax.swing.JMenu Teachers;
    private javax.swing.JMenuItem TeachersInfo;
    private javax.swing.JMenuItem ViewStudentList;
    private javax.swing.JMenuItem ViewTeachersList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
